### ISSUE TITLE
The custodian <> issuer relationship is not evidenced in the UI

### ISSUE THREAD

**Issue by Sarahb-da** [digital-asset/da-marketplace#44]

**Comment by alexgraham-da** [comment]
https://github.com/digital-asset/da-marketplace/pull/76 will add the list of Custodian Relationships to `Issuer`, `Exchange`, `Broker`, and `Investor` main UI pages. If that is not what this ticket was referring to, please let me know.

**Comment by alexgraham-da** [comment]
Addressed in https://github.com/digital-asset/da-marketplace/pull/76
