### ISSUE TITLE
Type 'number' inputs don't validate against quantity precision

### ISSUE THREAD

**Issue by alexmatson-da** [digital-asset/da-marketplace#94]
Although the `BTC` asset has a `quantityPrecision` of 6, trying to enter in a decimal value results in the following browser error:

![Screen Shot 2020-10-08 at 1 37 18 PM](https://user-images.githubusercontent.com/64022527/95494141-70969700-096b-11eb-903b-b571c6806c12.png)

Solution: set the step attribute on the input `<input type='number' placeholder='0.000000' step='0.000001'/>`

**Comment by Sarahb-da** [comment]
I will look at this
